e_commerce:
  outputs:
    dev:
      dataset: e_commerce_dataset_bronze
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: e-commerce-484010
      threads: 1
      type: bigquery
  target: dev
