e_commerce:
  outputs:
    dev:
      dataset: e_commerce_dataset_bronze
      job_execution_timeout_seconds: 30
      job_retries: 1
      location: us-central1
      method: oauth
      priority: interactive
      project: e-commerce-484010
      threads: 4
      type: bigquery
  target: dev
